### ISSUE TITLE
classlarni nomlashdagi hatolar

### ISSUE THREAD

**Issue by otabek-oktamov** [oybek94/crowdfunding-product-page#1]
https://github.com/oybek94/crowdfunding-product-page/blob/c2c8d89dfafc9877da640cdfbe7ed57dc927b3f9/index.html#L18

classlarni nomlashda aniq bir uslub ishlatilmagan yani navbar qismida bem uslubidan foydalanilgan 

qolgan qismlarda classlar oddiy uslubda nomlangan

**Comment by oybek94** [comment]
Gurux bo`lib ishlangan shu sababli uslublar bir biriga togri kelmay qolgan
