### ISSUE TITLE
Another color used for button

### ISSUE THREAD

**Issue by kozimov786** [oybek94/crowdfunding-product-page#2]
Current state :  ![Screenshot btn](https://user-images.githubusercontent.com/79497700/109601615-03191c00-7b41-11eb-8d63-9bb2a0e2caf4.png)
 Expecte State
![btn task](https://user-images.githubusercontent.com/79497700/109601731-33f95100-7b41-11eb-828c-f8767cb228bc.png)

**Comment by oybek94** [comment]
Thanks. Button border removed.
